version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_USER: user
  pg:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/pgdatabase:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test